// src/hook.ts — re-export shim (PLAN-lib-layer chunk 3)
//
// All hook logic now lives in src/adapters/hooks/. This file re-exports
// everything for backwards compatibility: test/hook.test.ts,
// src/digest/collect.ts, and the generated OpenCode plugin all import
// from this path.

export {
  COMMIT_HINT_MIN_COMMITS,
  type CommitHintInput,
  type ContextLineData,
  capContext,
  cmdHookEditHint,
  cmdHookReadHint,
  cmdHookSessionStart,
  cmdHookStop,
  commitHintFor,
  computeHintImpact,
  cursorTranscriptPath,
  decideStop,
  type EditHintInput,
  type EditTrackRow,
  editHintFor,
  editTrackPath,
  type HintFireRow,
  type HintImpact,
  hintLogDir,
  hintLogPath,
  hookTsMs,
  isCodexPayload,
  isCursorPayload,
  type NormalizedStopInput,
  normalizeStopInput,
  type RawStopPayload,
  READ_HINT_MIN_BYTES,
  READ_HINT_MIN_LIMIT,
  type ReadHintInput,
  type ReadTrackRow,
  type RereadHintInput,
  readContextData,
  readContextLines,
  readHintFor,
  readTrackPath,
  recordHintFire,
  rereadHintFor,
  SESSION_START_MAX_CHARS,
  type StopClient,
  sessionKey,
  sessionStartContext,
  stopBlockedBefore,
  stopBlockPath,
  stopOutput,
  utcStamp,
  worktreeKey,
} from "./adapters/hooks/index.js";
