// src/hook.ts — re-export shim (PLAN-lib-layer chunk 3)
//
// All hook logic now lives in src/adapters/hooks/. This file re-exports
// everything for backwards compatibility: test/hook.test.ts,
// src/digest/collect.ts, and the generated OpenCode plugin all import
// from this path.

export {
  COMMIT_HINT_MIN_COMMITS,
  type CommitHintInput,
  type ContextLineData,
  capContext,
  cmdHookEditHint,
  cmdHookMvGuard,
  cmdHookReadHint,
  cmdHookSessionStart,
  cmdHookStop,
  commitHintFor,
  computeHintImpact,
  cursorTranscriptPath,
  decideStop,
  type EditHintInput,
  type EditTrackRow,
  editHintFor,
  editTrackPath,
  GIT_AUTONOMY_COMMIT_POLICY,
  GIT_AUTONOMY_PLUGIN_FILE,
  GIT_AUTONOMY_PLUGIN_NAME,
  GIT_AUTONOMY_SYSTEM_REWRITES,
  GIT_AUTONOMY_TOOL_POLICY,
  GIT_AUTONOMY_TOOL_REWRITES,
  type GitAutonomyRewrite,
  type GitAutonomyStatus,
  type GitAutonomyToolRewrite,
  gitAutonomyStatus,
  type HintFireRow,
  type HintImpact,
  hintLogDir,
  hintLogPath,
  hookTsMs,
  isCodexPayload,
  isCursorPayload,
  mvGuardDecision,
  type NormalizedStopInput,
  normalizeStopInput,
  type RawStopPayload,
  READ_HINT_MIN_BYTES,
  READ_HINT_MIN_LIMIT,
  type ReadHintInput,
  type ReadTrackRow,
  type RereadHintInput,
  readContextData,
  readContextLines,
  readHintFor,
  readTrackPath,
  recordHintFire,
  rereadHintFor,
  rewriteGitAutonomySystem,
  rewriteGitAutonomyTool,
  SESSION_START_MAX_CHARS,
  type StopClient,
  sessionKey,
  sessionStartContext,
  stopBlockedBefore,
  stopBlockPath,
  stopOutput,
  utcStamp,
  worktreeKey,
} from "./adapters/hooks/index.js";
